version: '2'
services:
    tcs-app:
        image: tcs
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://tcs-mysql:3306/tcs?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8093:8093
    tcs-mysql:
        extends:
            file: mysql.yml
            service: tcs-mysql
