version: 2
registries:
  maven-repository-build-tis-nhs-uk-maven-repository:
    type: maven-repository
    url: https://build.tis.nhs.uk/maven/repository
    username: gradle
    password: "${{secrets.MAVEN_REPOSITORY_BUILD_TIS_NHS_UK_MAVEN_REPOSITORY_PASSWORD}}"

updates:
- package-ecosystem: maven
  directory: "/tcs-service"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jboss.resteasy:resteasy-client
    versions:
    - ">= 4.a, < 5"
  - dependency-name: org.jboss.resteasy:resteasy-client
    versions:
    - 3.14.0.Final
  registries:
  - maven-repository-build-tis-nhs-uk-maven-repository
- package-ecosystem: maven
  directory: "/tcs-client"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework:spring-test
    versions:
    - 5.3.2
    - 5.3.3
  - dependency-name: org.springframework.boot:spring-boot-test-autoconfigure
    versions:
    - 2.4.1
    - 2.4.2
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.6.28
    - 3.7.7
  - dependency-name: org.springframework:spring-context
    versions:
    - 5.3.2
    - 5.3.3
  - dependency-name: org.springframework.cloud:spring-cloud-contract-wiremock
    versions:
    - 3.0.0
  registries:
  - maven-repository-build-tis-nhs-uk-maven-repository
- package-ecosystem: maven
  directory: "/tcs-api"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.0
  - dependency-name: org.projectlombok:lombok
    versions:
    - 1.18.16
  registries:
  - maven-repository-build-tis-nhs-uk-maven-repository
- package-ecosystem: maven
  directory: "/tcs-persistence"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.1
    - 2.4.2
  - dependency-name: org.projectlombok:lombok
    versions:
    - 1.18.16
  registries:
  - maven-repository-build-tis-nhs-uk-maven-repository
