version: 2
registries:
  maven-jenkins:
    type: maven-repository
    url: https://build.tis.nhs.uk/maven/repository
    username: ${{secrets.JENKINS_MAVEN_USERNAME}}
    password: ${{secrets.JENKINS_MAVEN_PASSWORD}}

updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    registries:
      - maven-jenkins
    reviewers:
      - Health-Education-England/internal-admin-backend

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - Health-Education-England/internal-admin-backend
      - Health-Education-England/internal-admin-devops
