package com.transformuk.hee.tis.domain.enumeration;

/**
 * The CurriculumSubType enumeration.
 */
public enum CurriculumSubType {
	MEDICAL_CURRICULUM, MEDICAL_SPR, DENTAL_CURRICULUM, DENTAL_SPR, SUB_SPECIALTY, DENTAL_POST_CCST, ACF_OTHER_FUNDING, ACL, AFT, ACL_OTHER_FUNDING, CLINICAL_LECTURER, CLINICAL_TEACHING_FELLOW, CLINICAL_RESEARCH_FELLOW, ACFNIHR_FUNDING, ACLNIHR_FUNDING, OTHER_FELLOWSHIP
}
