ALTER TABLE `Person`
MODIFY `amendedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `Person`
MODIFY `addedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `Person`
MODIFY `inactiveDate` DATETIME NULL;

ALTER TABLE `ContactDetails`
ADD COLUMN `amendedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `PersonalDetails`
ADD COLUMN `amendedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `GmcDetails`
ADD COLUMN `amendedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `GdcDetails`
ADD COLUMN `amendedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `Qualification`
ADD COLUMN `amendedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `ProgrammeMembership`
ADD COLUMN `amendedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `RightToWork`
ADD COLUMN `amendedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;


