ALTER TABLE `Person`
MODIFY `amendedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE `ContactDetails`
MODIFY `amendedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE `PersonalDetails`
MODIFY `amendedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE `GmcDetails`
MODIFY `amendedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE `GdcDetails`
MODIFY `amendedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE `Qualification`
MODIFY `amendedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE `ProgrammeMembership`
MODIFY `amendedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE `RightToWork`
MODIFY `amendedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);


