CREATE TABLE `EsrNotification` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `notificationTitleCode` varchar(255),
  `deaneryBody` varchar(255),
  `deaneryPostNumber` varchar(255),
  `managingDeaneryBodyCode` varchar(255),
  `occupationCode` varchar(255),
  `hostLeadEmployerStatus` varchar(255),
  `newTrainingPositionLocation` varchar(255),
  `currentTraineeLastName` varchar(255),
  `currentTraineeFirstName` varchar(255),
  `currentTraineeGmcNumber` varchar(255),
  `currentTraineeProjectedEndDate` DATE,
  `currentTraineeVpdForNextPlacement` varchar(255),
  `nextAppointmentTraineeLastName` varchar(255),
  `nextAppointmentTraineeFirstName` varchar(255),
  `nextAppointmentTraineeGmcNumber` varchar(255),
  `nextAppointmentCurrentPlacementVpd` varchar(255),
  `nextAppointmentProjectedStartDate` DATE,
  `nextAppointmentTraineeEmailAddress` varchar(255),
  `nextAppointmentTraineeGrade` varchar(255),
  `withdrawnTraineeLastName` varchar(255),
  `withdrawnTraineeFirstName` varchar(255),
  `withdrawnTraineeGmcNumber` varchar(255),
  `withdrawalReason` varchar(255),
  `replacementTraineeLastName` varchar(255),
  `replacementTraineeFirstName` varchar(255),
  `replacementTraineeGmcNumber` varchar(255),
  `replacementTraineeCurrentPlacementVpd` varchar(255),
  `replacementTraineeProjectedHireDate` DATE,
  `changeOfProjectedHireDate` DATE,
  `changeOfProjectedEndDate` DATE,
  `postSpeciality` varchar(255),
  `workingHourIndicator` varchar(255),
  `postVacantAtNextRotation` varchar(255),
  `medicalRotationPostDeleteIndicator` varchar(255), -- long
  `createdDate` timestamp default now(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
